### ISSUE TITLE
Recover open tabs

### ISSUE THREAD

**Issue by josersleal** [davestewart/great-suspender-recovery-tool#3]
Great work...

Suggestion:

Recover open tabs.

In my case I have sessions saved that when I open bring up a number of tabs in several windows that are suspended.

The extension should go trough the tabs on each window and get from the end of the url (containing the previous extension text) the 'unsuspended url' and then load that url in sequence.

for example:

un-suspended url: 
extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=sometitle&pos=0&uri=http://www.goodurl.com/

Good url to load:
http://www.goodurl.com/

**Comment by davestewart** [comment]
Hey. You mean use the [Sessions API](https://developer.chrome.com/docs/extensions/reference/sessions/)?

**Comment by joeytwiddle** [comment]
I guess OP was talking about a session manager, such as [FreshStart](https://chrome.google.com/webstore/detail/freshstart-cross-browser/nmidkjogcjnnlfimjcedenagjfacpobb?hl=en).

I think I can give a pretty similar use case, but with bookmarks:

1. You have old bookmarks made with the original Great Suspender
2. You try to open this bookmark.
   But the URL is `chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#uri=.....`
3. So Chrome says:
   `This page has been blocked by Chrome`
   `ERR_BLOCKED_BY_CLIENT`
   Fair enough, since I don't have the Great Suspender installed any longer.

### Solution?

I suspect GSRT cannot act on that page, because it can't register itself as extension `klbibkeccnjlkjkiokjodocebajanakg`

Therefore I suggest this solution:

4. User copies the URL
5. User opens GSRT, and pastes the URL
6. GSRT extracts the good part of the URL, and opens it in a tab
   (Ideally at this point, both the original tab and GSRT would disappear, since right now I only really want that webpage)

Of course, if you can manage a better solution, e.g. detecting that broken page automatically, that would be great!

When I tried, it didn't appear in my browser history, so GSRT couldn't pick it up.

### Some example URLs

You may bookmark these if you want to test this flow.

```
# The user can fix this one easily enough, by simply deleting up to the =
chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#uri=https://news.ycombinator.com/item?id=10930718

# But this one has become encoded somehow, possibly because it was passed through a bookmark manager
# If GSRT could help the user to decode that, that would help to fulfil its mission
chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#url=http%3A%2F%2Fheavy.com%2Ftech%2F2015%2F10%2Flastpass-alternatives-logmein-acquired-replacements-password-manager-dashlane-keepass-1password-splikity-shark-tank-encryptr-enpass%2F
```

**Comment by davestewart** [comment]
Hi there.

I probably won't put any more effort into this extension now, as it was intended to work "at the time" but of course it is open source if you / the OP has the skill / inclination to pick up on this!
